refactor: change from global error enum to anyhow (#218)
### Description

This changes to use [anyhow](https://docs.rs/anyhow/latest/anyhow/)
instead of a "global" error enum. This does not fully tackle adding
context to places where errors happens, but more replace on places where
it was straightforward to change one for the other.

As a follow-up, should go on places that we currently have `.unwrap()`,
`.expect()` and some `?` to add `.context()/.with_context()` to them.

### Difference of output
Before these changes, running `linkup status` before a state exists
(running `linkup start`) would result on this error:
```
Error: NoState("No such file or directory (os error 2)")
```

With these changes, this is the error:
```
Error: Failed to load local state

Caused by:
    0: Failed to read state file on "/Users/username/.linkup/state"
    1: No such file or directory (os error 2)
```

Closes SHIP-1866